# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту sealenochka@mail.ru,  если сборка упала
notifications:
  email:
    recipients:
      - sealenochka@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

env:

  global:

    - CODECOV_TOKEN="6770abc6-7799-4a44-b9b9-d92950784da2"
